# Website
url: https://strappazzon.github.io
baseurl: "/PD2-SuperBLT-Hasher"
title: "SuperBLT Hasher - Calculate PAYDAY 2 mods hashes"
description: "Calculate PAYDAY 2 mods hashes."
name: "SuperBLT Hasher"

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Excluded files, folders
exclude:
  - README.md

# Markdown
markdown: kramdown

# Kramdown
# See: https://kramdown.gettalong.org/options.html
kramdown:
  html_to_native: true
  input: GFM
  # Disable smart quotes
  smart_quotes: "apos,apos,quot,quot"
  syntax_highlighter: rouge
  # See: https://rouge-ruby.github.io/docs/#configuration
  syntax_highlighter_opts: {}

# CSS
sass:
  sourcemap: development
  style: compressed
